name: Generate Release Keystore
on:
  workflow_dispatch: {}
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with: {distribution: 'zulu', java-version: '17'}
      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias release -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -keypass "${{ secrets.KEYSTORE_PASSWORD }}" -dname "CN=Sam, OU=Dev, O=ContentLibrary, L=Tehran, S=Tehran, C=IR"
          base64 -w0 release-key.jks > release-key.b64
      - uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: |
            release-key.jks
            release-key.b64
